### ISSUE TITLE
Put playback speed button on the top toolbar instead of the menu

### ISSUE THREAD

**Issue by xCipheredz** [flackbash/AudioAnchor#105]
Since the space is unused I think it's a good place to put the button. It will save a tap and it will make changing speeds more comfortable. Thank you!

**Comment by flackbash** [comment]
The menu item for the speed control is already set to show "ifRoom". If it does not show then your screen is too small such that displaying the speed control would take space off the app title. (It might look like there is enough room, but Android would still display the menu title as "AudioAn...") The app title is - to be fair - not super important to see there, but I think it looks weird if the title is cut off and it makes the menu bar look overcrowded, so for now I'll rather leave it as is.
