### ISSUE TITLE
[feature request] Finer playback control

### ISSUE THREAD

**Issue by payasrelekar** [flackbash/AudioAnchor#107]
I have found 15% over normal speed (1.15x) is very comfortable while still speeding up general audio, applicable to many different types of media. Currently AudioAnchor allows playback control at intervals of 10%, can we make it finer for 5%? Or perhaps a slider so as to not discriminate against anybody with preference for 14% or 16%? Not to compare, but NewPipe has such option and it is very useful.

Otherwise, great app! Thanks a lot!

**Comment by flackbash** [comment]
I added finer playback speed control in f758abe655abb73e0aaf46adbf1071bc2345bc38 . This will be in release v2.2.3 which I already published here and which will be picked up by F-Droid within the next week.

Thanks for the suggestion.
