### ISSUE TITLE
[feature request] Display folder tree structure

### ISSUE THREAD

**Issue by robbbbit** [flackbash/AudioAnchor#109]
I have a lot of audio books and lectures etc. in different categories. So that I don't lose the overview, I have a corresponding folder structure. Unfortunately, I have not found a way to display the folder structure in AudioAnchor
and navigate through it. My wish would be to display the folders of the root folder (e.g. Audiobooks). Then I click on a folder and the subfolders or audio books in it are displayed. I do this until I reach the right audio book.
Is there a way to do this?

**Comment by flackbash** [comment]
There is no way to do this in AudioAnchor.
There is only the initial list of all audiobooks/directories you added and then there is for each such directory the list of audio files it contains.

There are just different ways of adding folders: either adding a directory that contains multiple subdirectories which contain audio files - in this case the list of audiobooks will show the subdirectories - or adding a directory that contains audio files - in this case the list of audiobooks will show this directory.
