### ISSUE TITLE
Feature request: Add setting to control lock screen cover display

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#110]
Hi. I prefer to *not* display the track "cover" on the lock screen. Can you add a setting for this?

**Comment by flackbash** [comment]
I don't want to bloat the settings with options that I believe are not useful for many people.
I don't think this is an option many people would use, but you can of course try to change my mind.

**Comment by JohnVeness** [comment]
Hi, thanks for the reply. I understand not wishing to overload with settings. I don't know how many people use it, but all the other audio players I use have such a setting (AntennaPod, NewPipe, VLC), if that's any indication.

One reason I wanted to remove it is because most of the audio files I play with AudioAnchor don't actually have any cover art, so AudioAnchor just uses the treble clef image. For some reason this is very low res on the lock screen so looks terrible!

**Comment by JohnVeness** [comment]
On lock screen:
![](https://i.imgur.com/9gRSooi.png)

For comparison, in the app:
![](https://i.imgur.com/O6hI89b.png)

**Comment by flackbash** [comment]
Oh ok, now I get it. I thought you were referring to the cover image on the notification on the lock screen, because on my phone with Android 9 the cover image is not displayed on the lock screen like in your screenshots.
So the cover image on the notification is fine, right?

Then such an option does indeed make sense to me. I'll have a look if there's an easy solution for this. Thanks for the suggestion.

**Comment by JohnVeness** [comment]
Ah, sorry I wasn't clear at first. I'm glad I added the screenshots as I wasn't initially going to bother!

Yes, it's the lock screen "wallpaper" changing that I dislike. The small image in the notification is fine.

I'm curious that your device doesn't show that - I've tried to look for a system-wide setting to stop all apps changing the lock screen background, but haven't found one.

Many thanks for looking into this.

**Comment by flackbash** [comment]
I added an option to control whether to show the cover image on the lockscreen. This will be in the next release.

After changing the settings in order for the change to take effect, you need to stop the current media session, i.e. below Android 11 pause playback and swipe the notification. When you start playback again, the cover image will be displayed or not displayed on the lock screen according to your settings.
