### ISSUE TITLE
"Mark all tracks as not started" not as expected with several albums (multi-select)

### ISSUE THREAD

**Issue by digisus** [flackbash/AudioAnchor#112]
Thanks for providing this great little app! :-)

When I long-touch more than one album to "reset" to be able to listen to them again, the function "Mark all tracks as not started" only resets the last one selected.

Expected behavior: All selected albums get reset/marked as not started.

Many thanks for looking into this, digisus

**Comment by flackbash** [comment]
Fixed. This will be in the next release :)
