### ISSUE TITLE
AUDIO DOES NOT PAUSE WHEN RECEIVING SOUND NOTIFICATION

### ISSUE THREAD

**Issue by G-i-o** [flackbash/AudioAnchor#114]
Hello.

Thank You for providing this little gem.

Just wanted to report....when I make or receive a call, while listening with AudioAnchor, the audio is placed on pause and restarted when the call has ended. However, this does not work with sound notifications.
So, for instance, when I go for long walks, I like to listen to podcasts and have a tracking app for my walk too. The tracking app sends me a voice notification every ten min to inform me on my progress and the notification lasts about 10-15 secs. During this time AudioAnchor lowers the volume for itself but does not pause. Hence, I lose those 10-15 seconds of the podcast.

This is in reference to the current latest version, 2.2.3, on Android 10 (Lineage equivalent).

**Comment by flackbash** [comment]
There is an option in the settings called "Duck audio when playback is interrupted" which was added in #101 thanks to @awaters1 . It is right now enabled by default (maybe I should change that). If you disable it I think you have what you're looking for. I'll close the issue, but if this does not fix your problem, feel free to reopen it.

**Comment by G-i-o** [comment]
I tried that with it on and off. Unfortunately, in
both cases the outcome is identical: when the
announcement come through, AudioAnchor lowers the
volume of the audio that is being played but it
does not stop it.

🙏️

**Comment by awaters1** [comment]
Can you share the name of the tracking app? I only tested the audio ducking feature that I added with Google Maps.  It is possible the other app isn't setting the right audio settings.

**Comment by G-i-o** [comment]
Sure. It's OpenTracks
(https://github.com/OpenTracksApp/OpenTracks ).

Beware, though, that Voice
(https://github.com/PaulWoitaschek/Voice ), an app
most similar to yours, has not this issue. When I
listen to Voice and then receive not just audio
notifications (any), calls etc. from any app but
any sound (even alarms from timers etc.), Voice
does stop and then restart the audio when the
sound have finished.

Hope it helps. 🙏️

**Comment by awaters1** [comment]
Thank you for the bug report, I did some testing and on my device with Android 7 it works, however, I tried an Android 9 device, and the audio didn't stop properly (so doesn't work).  I'll have to take a look into it a little more to figure out a fix.

**Comment by G-i-o** [comment]
Thank You for looking into this and so promptly.
Much appreciated. 🙏️

**Comment by flackbash** [comment]
Merged. This will be in the next release. Thanks for reporting @G-i-o and thanks for the fix @awaters1 !

**Comment by G-i-o** [comment]
Thank You Natalie & Awaters for promptly acting on
this. You've been great.

If there's a cryptocurrency address (Preferably
not BTC for environmental reasons) where I can
send a donation to support the project, I'll be
happy to do so.

Again, much appreciation. 🙏️

**Comment by flackbash** [comment]
Unfortunately, there is no cryptocurrency address to support the development of AudioAnchor, yet.
But thank you anyway, the thought counts :)

I added a PayPal donation link in the About section of the app now, since I've had requests about donations before (in case PayPal is an alternative for you).

I just published a new release which also includes @awaters1 fix for this issue, so it should be on F-Droid within the next few days :)

**Comment by G-i-o** [comment]
Thank You very much for this. Just started to use the updated version from F-Drod and it now works beautifully. :pray:
