### ISSUE TITLE
[Question] What is causing the scrolling of textView?

### ISSUE THREAD

**Issue by skyGtm** [flackbash/AudioAnchor#116]
I checked in `activity_album.xml`, there was `marquee_forever` and related xml entries. Here, I was able to disable scrolling text.
But for `MainActivity`, there was no similar thing in `activity_main.xml`. I looked the code `MainActivity.java`, but don't understand which statement was causing the `TextView` to scroll

Could someone point me what I'm missing?

For my personal use, I just wanted to disable scrolling text,(with multiline Text) because it was quite irritating.

**Comment by flackbash** [comment]
The design and behavior of a single item of the `ListView` in the `MainActivity` is defined in the `album_item.xml` file. If you want to disable the scrolling of a text that is too long to fit the screen, you need to remove `
android:ellipsize="marquee"` and `android:marqueeRepeatLimit="marquee_forever"` [here](https://github.com/flackbash/AudioAnchor/blob/18df4b04a2ca5ef1dd89bb4f600fa3868f3db6cc/app/src/main/res/layout/album_item.xml#L29).

Does that solve your issue?

**Comment by skyGtm** [comment]
It helped.
Thank you.
