### ISSUE TITLE
IMPROVE COLOR CONTRAST

### ISSUE THREAD

**Issue by G-i-o** [flackbash/AudioAnchor#118]
Hello.

I find it difficult to read the titles and distinguish audio in listening process from those not yet listened and those only partially listened to. This is for both light and dark theme.

If possible, I'd like to request a better contrast for the audio titles and the :heavy_check_mark: and :pause_button: marks on the left side of the audio title. Maybe a pure white-on-black for the dark theme  and a bright green color for the :heavy_check_mark: and red color for the :pause_button: or something like that rather than the current grey on black and dark grey on light grey.

Thank You!

**Comment by flackbash** [comment]
I had different colors for the "completed" and "started" marks in a very early version of AudioAnchor, but I didn't like it. I thought the view seemed more cluttered and confusing using different colors. Therefore I'm not planning on changing it back, sorry :/

**Comment by G-i-o** [comment]
OK I respect that but you leave me and people like
me unable to view the difference like this?

Also, what about disable people who could struggle
even more?

Maybe, they could simply have a more contrasting
color (ideally black and white, I suppose) between
the circle and the sign inside?

Thank You.
