### ISSUE TITLE
[Feature request] Add "fast bookmark" with no name

### ISSUE THREAD

**Issue by TontonManu** [flackbash/AudioAnchor#119]
Hello, I use to listen to audiobooks during my sport sessions, and AudioAnchor doesn't allow adding a bookmark without entering a name.
It's complicated for me to enter text while training (I have to stop, type text and restart my session), so I can't use this function.

I would appreciate a "fast bookmark" function, ideally "tap screen once on the bookmark button", and the bookmark would be added without even any confirmation.
You could allow this feature in the options screen (another useful option would be "emit a sound to confirm the recording of the bookmark").

Nice app anyway!

**Comment by flackbash** [comment]
See also #117 .

I like the idea of a "fast bookmark" option in the settings.
This would probably be implemented in such a way, that if this option is set, a click on the bookmark button will add a bookmark "Untitled" or "Untitled 01" without any confirmation. A title for a bookmark could then only be added by going to the Bookmarks view and editing the corresponding bookmark. Is that how you imagine it?

I don't want to clutter the settings with too many options, so I probably won't add the sound option you suggested. But a message could be displayed to inform the user that they successfully added a bookmark.

**Comment by TontonManu** [comment]
Hello, you perfectly understood my request! A fast bookmark option which wouldn't ask any confirmation.
OK for displaying a message to confirm the creation of the bookmark.

**Comment by jlnbdt** [comment]
Hello,

It would be cool if a shortcut to this fast bookmark feature was placed on the notification bar, near the fast forward button. And even on the lockscreen :-)

**Comment by flackbash** [comment]
I added an option in the settings to enable the quick bookmark feature. I also added the bookmark icon on the notification. This will be in the next release. Feel free to reopen or comment here if you see any problems with the new implementation.
