### ISSUE TITLE
Sleep timer enhancements

### ISSUE THREAD

**Issue by Sulter** [flackbash/AudioAnchor#12]
I would like to propose the following two new features to enhance the sleep timer.

## 1) Shake to reset timer
- Shaking the phone resets the sleep timer
- Force required to reset the timer is adjustable

## 2) Adjustable fade-out
- It's possible to adjust the fade-out time

**I'm willing to implement both features as two separate pull requests. But I want to make sure that those features are aligned with your vision.**

**Comment by flackbash** [comment]
Cool!

1) I like the idea. You can implement it as options in the settings: One option for whether shaking the phone should reset the timer and one where the user can set the required force to reset the timer.
2) I would also suggest to implement this as an option in the settings.

Nice ideas :) Looking forward to your PRs.

**Comment by Sulter** [comment]
Great @flackbash ! Since I'm already knees-deep in the whole sleep-timer business. I've got another suggestion :).

I would like to move the amount of minutes the sleep timer will run for, to the settings menu too.
The current sleep timer drop-down menu could either stay there, and simply activate/deactivate the sleep timer, or we could alternatively have another icon for it. [example icon](https://thenounproject.com/search/?q=sleep&i=2216308)

What do you think? As a bare minimum I would at least like to make the amount of minutes persistent, since I think the most normal use case is to pick the same amount.

**Comment by jubalh** [comment]
It's pretty normal that people want to set the sleep timer to a different value every time they use it.
You want to play a book while you are cleaning the house, for one hour.
You want to listen to a talk before falling asleep and you know you are pretty tired -> 10 minutes.
You want to listen to a talk and are quite awake -> 25 minutes.

I don't see why it would be a good idea to move this to the general preferences.

**Comment by Sulter** [comment]
@jubalh thanks for chipping in! It's definitely a valid point, so let's keep the ability to input a new value every time sleep timer is pressed. 
I would still prefer to have the last entered value as suggestion, agreed?
