### ISSUE TITLE
How can I increase playback speed?

### ISSUE THREAD

**Issue by erperion** [flackbash/AudioAnchor#120]
I would like to increase speed to 1.25x or 1.5. On player screen I have play/stop button and skip buttons (+/- 10/30), nothing else. And in settings I don't see any option as well. I'm using old phone with Android 4.4.2, AudioAnchor version is 2.2.4.

**Comment by panbroggi** [comment]
I find the option pressing the three dots up right. It may be accessible with the "contextual menu" button, if you have it.

**Comment by erperion** [comment]
In three dots menu or when I press phone menu button I have these options:
Go to
Bookmarks
Settings

**Comment by panbroggi** [comment]
Ah, I see. And what icons are on top at the left of the three dots? I have the bookmark and the sleep timer, but if there is enough space there should also be the playback speed control. It looks like a WiFi signal with a pointer.

**Comment by erperion** [comment]
> I have the bookmark and the sleep timer

I have those as well. I've made few [screenshots](https://imgur.com/a/Txrx7ua). You can see how it looks on my phone.

**Comment by panbroggi** [comment]
Ok, this seems a problem with the UI; it is probably better to wait for the maintainer to give their opinion.

**Comment by erperion** [comment]
Ok, I will. I've been using this app for some time and it works well but I've seen this feature being discussed here and I couldn't find it so I was confused a bit. Thanks for your assistance.

**Comment by flackbash** [comment]
Unfortunately, this functionality is only available for Android Version >= 6.0 Marshmallow (API 23). For previous versions, the Android MediaPlayer class which is used by AudioAnchor does not support speed control.

**Comment by erperion** [comment]
That's ok, app still works fine, not having this feature is not a big deal. Thanks for info.
