### ISSUE TITLE
Support for ‘skip to next/previous track’ (buttons and headset commands)

### ISSUE THREAD

**Issue by huftis** [flackbash/AudioAnchor#126]
AudioAnchor is perfect for listening to audiobooks, where you will listen to a whole book or an entire chapter (track). But for podcasts, I usually have folder full of episodes (usually from different podcasts), and will skip an entire episode (track) if I don’t find it interesting enough (after listening for a few minutes). However, AudioAnchor don’t provide next/previous buttons in the ‘current track’ UI for this. And when my headset sends a next/previous command, AudioAnchor instead does a fast-forward/rewind action.

So this is a wishlist for support for next/previous track actions. I see three possible implementations:

**Option 1:**

- Add an option in the settings to *replace* the ‘fast-forward 30 seconds’ and ‘rewind 30 seconds’ buttons with ‘next’/‘previous’ buttons (i.e., ‘skip to the beginning of the next track’ and ‘go to the beginning of the previous track’).
- (At the start or end of a folder, when there isn’t a next/previous track, the effect of the buttons would be to stop playback.)
- Interpret the ‘next’/‘previous’ actions from headsets etc. as real ‘next’/‘previous’ actions.

**Option 2:**
- Don’t an option in the settings, and just replace the 30-second fast-forward/rewind buttons with next/previous buttons (and do the other stuff listed above). I don’t know how popular the 30-second buttons are, i.e., if the users would be happy with this solution. If the 10-second buttons are too ‘slow’, perhaps they could be replaced by 15-second buttons, as a compromise.

**Option 3:**
- Add the above next/previous buttons as an *extra* set of buttons, outside the 30-second buttons. But then I think the UI would get crowded.

**Comment by flackbash** [comment]
I understand, I like option 1 the most because for 2: both buttons are popular with me :) and for 3: I also think it would get too crowded.

However, I would adjust your suggested option 1 such that the next/previous actions from the headset always correspond to the user setting.
Additionally, since AudioAnchor's main purpose is to remember the playback position, I would probably implement it in such a way, that the "next" action skips to the saved playback position of the next track (the beginning of the next track if the user has not listened to it yet) and similarly for the "previous" action to the saved playback position of the previous track.
That also means, that if the next track has already been completed, the "next" action skips to the end of that track.
What do you think?

**Comment by huftis** [comment]
Yes, having the ‘next’/‘previous’ action from the headset always correspond to the user settings for the buttons sounds like a good idea. Makes things simpler.

And having thought about this a bit more, and having used AudioAnchor with a headset and the *current* ‘previous’/‘next’ actions for quite some time, I have noticed the following:

I *often* want to skip to the next track, but *almost never* to a previous (i.e., usually a completed) track. Also, having a quick ‘rewind’ when I miss part of the dialogue on a podcast or audio book is useful. So the ideal setup would be for the left button to rewind and the right button to skip to the next track (or position). So would it be possible to let the user configure the left and right buttons independently? I know this would complicate the UI a bit, but hopefully not much. For example, instead of an

Outer buttons: Rewind/fast-forward | Previous/Next

option, there would be a:

Left button: Rewind | Previous
Right button: Fast-forward | Next

(Or with better label labels / option names … :smile:)

Regarding your last question, having previous/next mean the previous/next *position* instead of *track* also sounds fine.

**Comment by aleksfadini** [comment]
I second this, I think the headset commands also control wearable. I love AudioAnchor and it would be awesome if I could pause/rewind from my watch, as I do with other players.

Thank you for making this wonderful audiobook player!

**Comment by huftis** [comment]
Isn’t this basically already fixed by 1c8623ca3ec27c468e3dbd65d419d549a4d0b8ba? I now have three separate settings for the forward/backward buttons. And my headset controls the third set (the notification buttons). And if I move the slider all the way to the right, the button turns into a ‘next’/‘previous’ button. It seems to work perfectly. (Thanks, it was just what was needed to turn AudioAnchor into the perfect podcast player for me! 😀.)

The only strange thing is that icon to the right of the slider is always a ‘previous track’ button. But it (correctly) *acts* like a ‘next track’ button when it’s used on the forward buttons.

**Comment by flackbash** [comment]
Glad to hear it :) I hadn't tested the headset commands but if it works as expected then I agree, we can close this :)

But before, what do you mean with "icon to the right of the slider is always a ‘previous track’ button"? I attached a screenshot that shows the slider for one of the forward buttons. The icon on the right side of the slider is a 'next' icon. Or do you mean something else?

![photo5267168762069629704](https://user-images.githubusercontent.com/5568910/156892611-e272152a-aab0-4f4b-b22d-07f0a5c600b7.jpg)

**Comment by huftis** [comment]
Yes. On my system (self-built from Git or latest F-Droid version), the ‘next’ button does *not* look like in your screenshot. Both the orange image in the slider and the grey text after selecting it is *always* a ‘previous track’ button, independent of which button it is assigned to. This is the slider for ‘Forward button 1’:
![Screenshot_20220305-181042](https://user-images.githubusercontent.com/100251/156893450-62b3b55b-09b6-4568-af8a-f3390ca31ad7.png)

**Comment by huftis** [comment]
BTW, it is only in the settings that the wrong buttons are shown. In the main UI and the notification UI, the correct buttons are used.

**Comment by flackbash** [comment]
Wow, that's mysterious :) I'll see if I can find the problem.

**Comment by flackbash** [comment]
Uff, not so mysterious after all. Rather stupid. I distinguish between backward and forward skip button in the settings via the dialog title right now. Namely by whether the dialog title contains the word "forward". Which it does not in Norwegian... I'll come up with something.

**Comment by flackbash** [comment]
Should be fixed now.

**Comment by huftis** [comment]
> Should be fixed now.

I can confirm that it is fixed. Thanks!
