### ISSUE TITLE
Removing folders from library should NOT delete actual data

### ISSUE THREAD

**Issue by sam2kb** [flackbash/AudioAnchor#136]
Why would you physically delete the directory and its contents including all subfolders from filesystem. This is insane, you wouldn't find any other player or reader with this dangerous feature unless it's hidden by default or requires  a confirmation text field.

Yes I lost a whole `Downloads` directory with a bunch of files. Please turn off this madness.

**Comment by flackbash** [comment]
There is the option "Delete" and there is the option "Delete from database". In my opinion, if you decide not to go with the "Delete from database" option then it should be pretty clear that you are deleting the file from the file system. Additionally, there is a confirmation dialog that specifically asks you if you want to delete the files or folders and its contents. Did this confirmation dialog not appear in your case?
