### ISSUE TITLE
[feature request] Playback speed controls

### ISSUE THREAD

**Issue by LmarLoe** [flackbash/AudioAnchor#153]
I often change the playback speed. Especially during walking  it is difficult to set it precisely.  Buttons with + and - would be helpful; or for example ability to step adjustment; or a few customizable presets for speed
Thank you for your app

**Comment by flackbash** [comment]
Yes, I agree, + and - buttons would be helpful. I'll put it on my todo list.

**Comment by flackbash** [comment]
I added the buttons and it will be in the next release :)
