### ISSUE TITLE
Drop legacy com.getbase:floatingactionbutton

### ISSUE THREAD

**Issue by PatrykMis** [flackbash/AudioAnchor#156]
Version 1.10.1 is from 2015. It is only library which uses old android.support libraries, which requires Jetifier to be enabled.
Floating Action Button can be implemented usual way with Material library:

* [FloatingActionButton | Android Developers](https://developer.android.com/reference/com/google/android/material/floatingactionbutton/FloatingActionButton)
* [Add a Floating Action Button | Android Developers](https://developer.android.com/guide/topics/ui/floating-action-button)

**Comment by flackbash** [comment]
I am using a standard FloatingActionButton e.g. [here](https://github.com/flackbash/AudioAnchor/blob/a6e7321a30c8469faced57628c4b95ef03506dc2/app/src/main/res/layout/activity_main.xml#L30), but I need a special FloatingActionButton with two options (FloatingActionsMenu) [here](https://github.com/flackbash/AudioAnchor/blob/a6e7321a30c8469faced57628c4b95ef03506dc2/app/src/main/res/layout/activity_directory.xml#L31). This is why I'm using `com.getbase:floatingactionbutton`. You can view this FloatingActionsMenu button in the app when adding a new directory to your library. Do you know of better options for this use case?

**Comment by PatrykMis** [comment]
Unfortunately no.
I've just created [pull request](https://github.com/zendesk/android-floating-action-button/pull/394) so you can eventually fork it.

**Comment by TacoTheDank** [comment]
> Do you know of better options for this use case?

There are other libraries for this that are better maintained. I was actually looking at doing this for AudioAnchor but I forgot. I'll get this done :)
