### ISSUE TITLE
Cover image not cleared when moving to next/previous track

### ISSUE THREAD

**Issue by huftis** [flackbash/AudioAnchor#160]
When you listen to a track with a cover image and use the next/previous track button (or just let the current track play to end) to skip to a track that *doesn’t* have a cover image, the cover image is not cleared, i.e., the cover continues to be shown. In effect, the wrong cover image is shown (the ‘missing cover’ image should be shown).

However, if you use the back to folder navigation feature to select a track, this doesn’t happen (the cover image *is* correctly cleared).

I’ll attach an example. It’s a zip file with three files. The files `track-1.opus` and `track-3.opus` don’t have a cover image, while `track-2.opus` does.

To reproduce the bug, put the files in a folder and add the folder to AudioAnchor. Start playing `track-1.opus`. The default ‘no cover’ image is shown. Skip to `track-2.opus`. Cover image is (correctly) shown. Now skip to either `track-1.opus` or `track-3.opus` using the skip buttons (or let the track play for 15 seconds). The *same* cover image is (incorrectly) shown. If you instead use the back arrow at the top left to navigate back the folder view and select one of the two tracks, the ‘no cover’ image is shown.

[example-tracks-cover-bug.zip](https://github.com/flackbash/AudioAnchor/files/8549843/example-tracks-cover-bug.zip)

**Comment by flackbash** [comment]
I'll check it, thanks for reporting it!

**Comment by flackbash** [comment]
Done, thanks for the nice minimal example :)
