### ISSUE TITLE
v2.3.1 Unable to delete track from device

### ISSUE THREAD

**Issue by LmarLoe** [flackbash/AudioAnchor#165]
When trying to delete a file it is not deleted
Some logcat:
```
I/MediaProvider(4479):  Deleted 0 items on external_primary due to com.prangesoftwaresolutions.audioanchor
W/FuseDaemon(4479):  Handling plain readdir for trackname.mp3. Invalid d_ino
E/AlbumActivity(17140):  Update AlbumLastCompletedTime
```
This did not happen in v2.3.0
LineageOS 18.1 (Android 11)

**Comment by flackbash** [comment]
I can't reproduce this on my Android 9 phone, but Android 11 is .. special. LineageOS too unfortunately.

I'll try to reproduce it in an emulator when I have more time.

**Comment by flackbash** [comment]
This should be solved with 3835102731b3311032d7878efd8c0faeb8522a0a. I already published a new release and F-Droid should pick it up within the next days.

**Comment by brawnswubb** [comment]
@flackbash  I see...I only tried removing it from library when the 'delete from device' option didn't work. At any rate, I should've looked at releases before commenting! I tested on 2.3.2 and the problem is indeed fixed. I'll wait for the f-droid release, thanks for all you do!

**Comment by flackbash** [comment]
Great :)
