### ISSUE TITLE
Permant Crash on Google Pixel 3 

### ISSUE THREAD

**Issue by raven000xf** [flackbash/AudioAnchor#167]
Permant Crash on Google Pixel 3 (Android 12 latest patch level which possible, no custom ROM) 
Only deinstallation and return to 2.3.0 helps.
Installation of older versions over isn't possible, everytime problems with the 📦. Source was here and FDROID

**Comment by flackbash** [comment]
Thanks for reporting this! When does the crash happen? Directly when starting the app? When pressing play?

**Comment by andrewfarabee** [comment]
I think I have the same issue on OnePlus7t. AudioAnchor crashes immediately upon opening the app for the first time after updating from 2.3.0 to 2.3.1 in F-Droid.

**Comment by flackbash** [comment]
@andrewfarabee thanks for the reply.
And it continues crashing for you, too, or just upon opening it for the first time after updating?
Are you on Android 12, too?

**Comment by andrewfarabee** [comment]
I'm on Android 11. The app crashed everytime I tried to open it after the update to 2.3.1, but it is no longer crashing after clearing the app storage.

**Comment by flackbash** [comment]
Interesting, I'll try to reproduce it on the weekend. Although I think I tested it with both Android 11 and 12 before and it worked fine. But I'll look through the changes and see if I can find something that causes this behavior.

**Comment by raven000xf** [comment]
Directly crash at app start for me.

**Comment by pahool** [comment]
Same here on a OnePlus 6t on Android 11. Crashes on startup

**Comment by flackbash** [comment]
@raven000xf , @andrewfarabee , @pahool , it could help if some of you could get the logs from your device, e.g. with adb logcat (https://developer.android.com/studio/command-line/logcat) or AndroidStudio.

If not, I have a suspicion which commits might be the problematic ones. I can roll back the changes until before those commits and create an apk. Could some of you install the apk and check if the problem still occurs? That would at least narrow it down and in the worst case I can simply undo the potential problematic commits and publish a new release.
Best send me an email to the address [here](https://ad.informatik.uni-freiburg.de/staff/prange) then I'll send you the apk.

**Comment by flackbash** [comment]
The problem seems to have been a permission issue on Android versions >= 11 when targeting SDK 30.
Although I could still not reproduce the issue on an emulator, so there must have been some more factors involved.

I just published a release with target SDK version rolled back to 29. Fdroid should pick it up within the next week. Hopefully this solves the problem. Feel free to reopen this issue if it does not.

Thanks a lot all of you for your help!
