### ISSUE TITLE
Suggested Fix for Bug on API 26: Playback glitches back when starting from stored position

### ISSUE THREAD

**Issue by axoTheLotl** [flackbash/AudioAnchor#17]
Hey there,
thank you for this App!

I am new to Android-Development and cloned your code as a learning project.
When I started playing around with it I realized using my Phone (API 26) that the playback sometimes glitches back to the nearest full ten seconds (e.g. starting from 2:35 it goes to 2:30 or from 3:27 to 3:20). It happens when starting from a stored position, when jumping back/forward or when using the seekbar (so basically every time a mMediaplayer.seekTo(msc) is called). This could be replicated with a different phone (also API 26). The App didn't show this behaviour when run on a phone with API 25.

Since I'm learning here I jumped right in trying to find a solution and got something that now works for both API 26 and below. To keep up with etiquette I wanted to raise this issue beforehand and if it is appreciated I'd like to submit a PR on this. 

Note again that I'm not experienced (as not to say a noob...) but I'd highly appreciate feedback on my solution.

happy coding!
best 
Lotl

**Comment by flackbash** [comment]
You are very welcome to submit a PR, then I'll have a look at it and see if we can merge it.
I have a few questions beforehand, just to clarify things:

1) The app always showed this behavior every time when e.g. starting from a stored position with API 26? If not, were you able to figure out in which scenario exactly it happened?

2) Does the time stamp glitch back to the nearest full 10s or is it just the audio file that starts playing from that position? So, the playback starts from 2:30 but the time stamp still shows the 2:35 for example?

3) Did you do your tests with the same audio file every time? That is, your tests with API 25 and API 26 were performed with the same audio file?

4) Many standard audio players have problems with audio files that don't have a constant bit rate. The Android MediaPlayer which is used in AudioAnchor has this problem as well. You can check whether an audio file has a constant bit rate in the properties of that file.

**Comment by axoTheLotl** [comment]
So as it turns out the problem was actually with my audiofiles. I used different ones but they all came from the same source (audio downloading app). Using different files made the problem disappear. Rookie mistake...
Still funny that it was only a problem with API level 26 and that I found a fix. 

Since the issue is not really an issue I won't submit a PR. 
Hope to be able to contribute soon though!

**Comment by flackbash** [comment]
Hm interesting. Did you find out what might have caused the problem with the audio files? Was it the bit rate? 

> Hope to be able to contribute soon though!
Looking forward :)

**Comment by axoTheLotl** [comment]
Sorry for the very late reply.
I really don't know what is wrong with the files. If I put them through a converter (even if I "convert" them from m4a to m4a) they work fine...
Very strange issue. Than again, not a very crucial one : )

Anyway, I'm working on support for multiple directories now. Hope to be able to submit a PR soon.
regards,
Lotl

**Comment by JohnVeness** [comment]
Hello. I realise this is old and closed, but I was wondering what your fix was? It would be nice for the average user not to have to fix their files.
