### ISSUE TITLE
[feature request] "next file" button

### ISSUE THREAD

**Issue by lexillar** [flackbash/AudioAnchor#190]
I prefer manual switch between chapters, but in current interface I need to exit file and enter another. Adding button will be wonderful

**Comment by flackbash** [comment]
This feature already exists. Go to settings, scroll down to "Skip intervals", select one of the forward buttons and pull the slider all the way to the right side with the ">|" symbol. If you want to have the next file button on the notification, do the same for the "notification forward button".

**Comment by lexillar** [comment]
thank you. that was very unexpected setting)

**Comment by flackbash** [comment]
I should really write a documentation some day :)

**Comment by lexillar** [comment]
nobody reads documentation. may be theese measures could help:
- rename in settings button intervals -> button actions
- use screenshots with changed button in store
- may be 'how to use' demo for the first start
