### ISSUE TITLE
Selection of SD-Card = crash

### ISSUE THREAD

**Issue by gthbbr** [flackbash/AudioAnchor#2]
Expected behaviour:
Select music folder on SD-Card as primary music folder.
--
What happens (everytime):
1. Open AudioAnchor
2. Click on bread crumbs -> "choose library"
3. music folder on main storage is shown, bc it was automatically set as music folder
4. I press 2 times on "..." to go up in the folder hierarchy
5. As I press the second time on "..." I expect to go from "/0/emulated/" to "/0/" to be able chose the SD-Card, but...
6. App crashes instantly without any message or lag
--
Device:
Galaxy S9
...
Idea:
Permissions to access the sd card? Some other apps also cannot write to sd card, but only a few.

Thanks in advance

Awesome App btw! Every music app should have your track progress function integrated.

**Comment by flackbash** [comment]
Thanks for reporting this. I just observed the bug some minutes ago and added a quick fix with 4e948b5ca221b5297effe43db726ee0ab00e8667. This prevents the app from crashing but it doesn't seem to fix the issue entirely. Some directories are still not being shown, but at least I was able to navigate to the sd card. Let me know if this works for you and I'll try to have a closer look at it soon.

**Comment by gthbbr** [comment]
Great. Maybe this will help?

https://stackoverflow.com/questions/52417108/cannot-write-to-sd-card-on-android

**Comment by flackbash** [comment]
At that point the app is just reading from the sd card. Also, the app asks for permission to read the external storage so it should be something else.

**Comment by flackbash** [comment]
The problem seems to be that I need root privileges to navigate to certain directories in newer Android versions. Accessing the SD card should be fine as well as accessing the device storage but I don't have permission to read `/storage/emulated/`. I'm not sure yet how to solve this nicely but I'll come back to it.

**Comment by gthbbr** [comment]
Just to give feedback:
From Version 1.8 (F-Droid) the issue is gone (music playback works also). Great work! Thx! 👍

**Comment by flackbash** [comment]
Perfect, thanks for the feedback.

**Comment by vnord** [comment]
I seem to have a related issue -- when I try to play files on the external SD card it simply says "There is a problem with the audio files in this directory". Files on the internal storage work fine.

**Comment by jubalh** [comment]
Are the files playable by other audio players? Do you have read permission?

**Comment by vnord** [comment]
> Are the files playable by other audio players? Do you have read permission?

Yes on both counts, though write access seems to be missing (I'm trying to figure out how to grant that).
