### ISSUE TITLE
Syncing files

### ISSUE THREAD

**Issue by hundchen123** [flackbash/AudioAnchor#201]
Hi Natalie,

I recently installed auioanchor 2.3.3 (29) on my android 5.0.2 mobile phone for listening to podcasts, as my earlier audio player had stopped working properly.  I really like the simple clean interfce and the fact it saves my place. 

I have my files installed on my SD card and regularly tranfer new files over from my pc and delete the old ones.  I have seen the option to “sync files” appear a couple of times but can not find how to trigger the function.  Can you help please?

Many thanks,

Judy

**Comment by hundchen123** [comment]
PS.  Sorry now realised it's an option in the menu on the opening page.

**Comment by flackbash** [comment]
Hi Judy, glad you like the app :) You can also simply pull down the list of albums / audio files (that is, scroll up when you're already at the very top of the list and you'll see a little circular arrow).
Best regards
Natalie
