### ISSUE TITLE
Unpause on bluetooth headset button press almost doesn't work

### ISSUE THREAD

**Issue by Self-Perfection** [flackbash/AudioAnchor#29]
AudioAnchor courteously responds to bluetooth headset button press during playback and pauses playback.

But after that AudioAnchor almost never responds to bt headset button while it is paused. Rarely AudioAnchor unpauses playback, but in most cases it does not respond at all.

For comparison https://github.com/TeamNewPipe/NewPipe always unpauses with the same headset.

**Comment by Sulter** [comment]
It's impossible to know what kind of events your headset sends and when. You will need to see which KeyEvent your bluetooth headset sends.
Refer to #14 for more details, we had a similar issue with a headset.

**Comment by Self-Perfection** [comment]
Can you give me advice how I can check which events sends my headset? Just in case, it is JBL Tune 205 BT

We can also check how bluetooth headset buttons handling is implemented in another, that does this reliably. I tried to find corresponding place in NewPipe sources but failed. `git grep --ignore-case KEYCODE` in NewPipe repository finds only one match unrelated to pause handling. Is it possible NewPipe uses completely different approach to this task?

**Comment by Sulter** [comment]
> Can you give me advice how I can check which events sends my headset? Just in case, it is JBL Tune 205 BT

You need to set a breakpoint in the code, while it runs on your device. Set it on the
action == KeyEvent.ACTION_DOWN 

> We can also check how bluetooth headset buttons handling is implemented in another, that does this reliably. I tried to find corresponding place in NewPipe sources but failed. `git grep --ignore-case KEYCODE` in NewPipe repository finds only one match unrelated to pause handling. Is it possible NewPipe uses completely different approach to this task?

Very possible, might be worth looking into.

**Comment by flackbash** [comment]
I've had a similar problem. To me it seems to be somehow time-related (and therefore tedious to debug :/). After a while on pause and without interaction with the app (maybe around 10 mins on my phone) it does not respond to headset button events anymore. It responds perfectly fine when I just only started playback in the app and then immediately send a couple of headset button events.

Is it the same in your case @Self-Perfection ?
@Sulter have you experienced something like this with AudioAnchor?

Interestingly, if I don't interact with the app for a shorter while (maybe 5 mins), then press the headset button to start playback, it takes longer to respond to the button event, but after 2, 3 seconds the playback is still started.

I'll have a closer look at the issue and check out NewPipe and/or other apps but it might take around two weeks until I get the time to do so.

**Comment by Self-Perfection** [comment]
> You need to set a breakpoint in the code, while it runs on your device. Set it on the
action == KeyEvent.ACTION_DOWN

This is complicated for me, I'm not an android developer. I hoped there is logging app showing pressed buttons codes.

>After a while on pause and without interaction with the app (maybe around 10 mins on my phone) it does not respond to headset button events anymore. It responds perfectly fine when I just only started playback in the app and then immediately send a couple of headset button events.

@flackbash, I have similar feeling! It seems to me AudioAcnhor sometimes responds to headset button if I press it within ~30 seconds of pausing, but never responds if I wait longer. But I don't have enough observations to be sure of that.
