### ISSUE TITLE
Increase playback speed

### ISSUE THREAD

**Issue by deniss-s** [flackbash/AudioAnchor#36]

**Comment by deniss-s** [comment]
Currently it's possible to set playback speed up to x2.5. For me this is not enough I would go at least till x3.
I understand that there are not so many users who listen at such speed, but it's always better to have some reserve. VLC, by the way has upper limit at x4.

**Comment by flackbash** [comment]
I personally never use a speed up > 2x but I would agree with you that it's better to have that reserve. On the other hand I have already received complaints that 2.5x is too much ;)
So I'll think about it. If anyone else has an opinion on this let us know.
A good option might be to go up to 3x and add a reset button that resets the playback speed to 1x.

**Comment by deniss-s** [comment]
Maybe it's possible to find a middle ground by using 2x as default limit, but add a possibility to increase in it the settings.
Also Antenapod has quite interesting solution. They provide a list with playback speeds in settings from which you select those that you prefer. E.g. 1x, 1.5x, 1.75, then during the playback you can cycle through selected speeds by tapping appropriate button.

**Comment by flackbash** [comment]
I set the maximum playback speed to 3x and added a reset button to reset the speed to 1x. I don't want to clutter up the settings too much so I think this is a good solution for now.
