### ISSUE TITLE
Add support for .aac files

### ISSUE THREAD

**Issue by Russe** [flackbash/AudioAnchor#37]
Currently .m4a files are supported, but files with .aac as filename extension are not recognized by the player.
When changing filename extension from .aac to .m4a these files are recognized and well played.
So for me it seems that only the filename extension needs to be enabled as supported file type.
Could you add support for .aac?

**Comment by flackbash** [comment]
Done.

**Comment by Russe** [comment]
Thanks a lot, love it.
