### ISSUE TITLE
[Help] Am I syncing wrong?

### ISSUE THREAD

**Issue by Devorlon** [flackbash/AudioAnchor#4]
Hi, 

Sorry for the clickbaity title but when exporting the database or 'syncing' nothing happens.

The fine audioanchor.db exists but when I read it with a sql reader it shows nothing. and when I import it on another device the position does not sync or the bookmarks.

Am I missing something?

**Comment by flackbash** [comment]
I haven't documented the usage of the import/export/synchronize functionality anywhere so just to make sure you did everything the way it's supposed to be done:
You have installed AudioAnchor on device A. You used the export functionality on that device to get the file audioanchor.db. On device B, you have installed AudioAnchor as well. You have the same directory structure (same directory names and file names relative to a given a parent directory) for your audio files and you have selected that parent directory in AudioAnchor of device B such that the same folders and files as on device A are showing (or at least those for which you want to import the progress). Then you perform an import on device B from the audioanchor.db file which you created on device A and click synchronize. And then nothing happens?

If so, which AudioAnchor version are you using? Is it the same on both devices?
When you click import database do you get the message "Import successful"?
When you click synchronize, do you get the message "Synchronized directory"?

**Comment by flackbash** [comment]
I assume my explanation solved your problem.
