### ISSUE TITLE
Show progress in time and percent

### ISSUE THREAD

**Issue by krmax44** [flackbash/AudioAnchor#40]
Instead of toggling between showing progress in time or percent, it'd be nice to see both of them simultaneously.

**Comment by flackbash** [comment]
Honestly, I think this would look weird. Maybe I'm just being unimaginative, but I also don't want to clutter up the settings too much with options which I think hardly anyone will use. So unless this request is seconded I'll not implement this. Thanks anyway for the suggestion :)
