### ISSUE TITLE
Add an About screen

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#44]
It would be nice to have an About screen in the menu, to see version number, link to GitHub etc.

**Comment by jubalh** [comment]
How about you click on "..." and then "about" ? ;)

**Comment by JohnVeness** [comment]
I see no such option in 2.0 from F-Droid, but if you're saying it's coming soon, great :)

**Comment by flackbash** [comment]
I did not make the About activity accessible from all activities because I think that it's not an essential activity that users will refer to a lot and I do not want to clutter up the menus. But I did add a link to this repo in the About activity. Thanks for the suggestion!
