### ISSUE TITLE
Support for Opus codec

### ISSUE THREAD

**Issue by Gitouisl** [flackbash/AudioAnchor#47]
I would use [Opus](https://www.opus-codec.org/docs/) files in the app if they were supported, I would think I'm not the only one - for audiobooks it's [essentially transparent](http://wiki.hydrogenaud.io/index.php?title=Opus#Speech_encoding_quality) at 32kbps instead of the 64kbps I used to use for mp3.

**Comment by flackbash** [comment]
Are the files not shown in the list of audio files within AudioAnchor or are they not playable?
What file extension do they have? AudioAnchor decides which files to show based on the file extension. If your Opus files have a .ogg or .mkv ending they should at least be shown in the list of audio files.

Which Android version are you using? Apparently Opus is only [supported](https://developer.android.com/guide/topics/media/media-formats) starting from Android 5.0 .

**Comment by Gitouisl** [comment]
I'm using Android 9. The opus files do not show in the list: 'No audio files found in this album'. The files have .opus as the extension, as my encoders give them by default. From [Wikipedia](https://en.wikipedia.org/wiki/Opus_%28audio_format%29#Containers): "Opus was originally specified for encapsulation in Ogg containers, specified as audio/ogg; codecs=opus, and for Ogg Opus files the .opus filename extension is recommended." I hope this helps!

**Comment by flackbash** [comment]
Can you check if it works if you just change the file extension to .ogg? Then it would probably be enough to add .opus to the list of supported file extensions.

**Comment by Gitouisl** [comment]
No, a test file wouldn't show up as an ogg file either after I changed the extension, and I even did a fresh 'Choose directory,' after changing it.

**Comment by flackbash** [comment]
Did you also press the refresh/sync button in the Main Activity?

**Comment by Gitouisl** [comment]
Yes, I did that first, but wasn't sure it was enough when it didn't show the file, so then I redid the 'Choose directory' after that.

**Comment by flackbash** [comment]
Yes, syncing should be enough. Hm that's weird... 
I just performed some experiments and added an .ogg extension to an image which caused AudioAnchor to close upon syncing. Did the same happen in your case?

**Comment by Gitouisl** [comment]
No, I would have mentioned that! I just tried changing the extension to both ogg then opus, and then adding both to the jpg extension, and neither crashed AudioAnchor. But like before, it didn't see any of those. I also tried changing the jpg extension to mp3 and it wasn't visible either, although actual mp3 files in other folders are are working fine.

**Comment by flackbash** [comment]
Yes, the minimization is what I meant. If it does that upon changing the extension to .ogg it probably means that the Android MediaMetadataRetriever can not handle your files. In that case I can't add support for it.
The minimization should of course not happen, but that's another issue.

**Comment by Gitouisl** [comment]
Ah, okay. Opus files do work for me in [Listen Audiobook Player](https://play.google.com/store/apps/details?id=com.acmeandroid.listen&hl=en_US) (and my music player) so I'll keep using that for them.

**Comment by tzh1043** [comment]
Using version 2.1.3 on Android 8, I can get Opus data to play when I re-pack it into an `.mkv` container.

But as in other Apps, _seeking_ does not work, so this seems to be an underlying Android problem. Upgrading to 9 at least brings support for some rudimentary forward-seeking. VLC includes its own decoder so it does not have that problem.

**Comment by flackbash** [comment]
Interesting, thanks for the info.
