### ISSUE TITLE
Hide files/folders starting with a dot

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#49]
I have files and folders that start with a dot. It would be good if these were hidden by AudioAnchor by default, maybe with an option to show them.

**Comment by flackbash** [comment]
Good point. I'll implement it.

**Comment by flackbash** [comment]
Done. I implemented an option to show hidden files and they are hidden by default.
After changing the settings option, one needs to do a sync for the change to take effect.

**Comment by flackbash** [comment]
The synchronization now happens automatically after the settings change.

**Comment by JohnVeness** [comment]
Many thanks for this. After updating the app I had to do one sync before the dotfiles were hidden, but everything seemed fine after that.

I don't know if you can automate a sync if you detect a version change in future..?

**Comment by flackbash** [comment]
I believe I actually can't (in a clean way) because so far I don't keep any reference of a user's previously installed version. But I should consider this for future updates. Thanks for pointing it out.
