### ISSUE TITLE
Sorting is wrong 

### ISSUE THREAD

**Issue by srbhp** [flackbash/AudioAnchor#5]
Thanks for the app.
May you please fix sorting of the files? I think this happens for more than 9 files. 
![Screenshot_20190507-184731](https://user-images.githubusercontent.com/1505628/57317677-f704d480-70f8-11e9-8e05-0f75e3709748.jpg)

**Comment by flackbash** [comment]
The error occurred because the sorting of the files was done alphabetically, so the items "1 A", "2 A", "12 A" were sorted as "1 A", "12 A", "2 A". In commit 8f271a9 I implement alpha numerical sorting which should fix this. I will publish a new release soon.
Thanks for reporting this.

**Comment by srbhp** [comment]
Thanks a lot.
