### ISSUE TITLE
Option for sleep timer

### ISSUE THREAD

**Issue by Ulafa** [flackbash/AudioAnchor#53]
Hi,
could you add an option for the sleep timer, which stops playback not where you are at the end of the counter, but at the end of the file? Sometimes I don't want to end in the middle of a 5 minute file.
That would be great, because I really like your app.

**Comment by flackbash** [comment]
Do I understand you correctly: you want autoplay enabled and want to listen to possibly several files while the sleep timer is running, but once the sleep timer has stopped you want to continue listening until the end of the file, right?

**Comment by Ulafa** [comment]
Thats exactly what I wanted to say! My English is a little bit rudimentary 😄

**Comment by flackbash** [comment]
Nice suggestion :) I implemented this and it will be in the next release.
