### ISSUE TITLE
Behavior: audio books with more than 100 files

### ISSUE THREAD

**Issue by Ulafa** [flackbash/AudioAnchor#55]
My audio books consist of more than 100 files and have the following naming scheme: number - name.file format
Whenever I reach the tenth file, the player jumps to file number 100, so it skips files 10-99.
A inconvenient workaround is to add three digits to the numbers in the file name.
Is there a possibility to fix this?

PS: Thanks for your help with the sleep timer. I look forward to it :)

**Comment by flackbash** [comment]
Fixed. Thanks for reporting it!
