### ISSUE TITLE
Scrolling down in audio book file list

### ISSUE THREAD

**Issue by Ulafa** [flackbash/AudioAnchor#56]
At the moment AudioAnchor doesn't remember the last position in the file overview of each audio book. It would be nice, if AudioAnchor could jump to the last file, which played.

**Comment by flackbash** [comment]
Right now it jumps to the first not completed file. But I agree that in most cases the last played file probably makes more sense.

**Comment by Ulafa** [comment]
I've updated to Android 11 and when I open a book AudioAnchor jumps always to the first file instead of the last played file.

**Comment by flackbash** [comment]
Right, I fixed it and in the next release it should jump to the most recently played file.
