### ISSUE TITLE
Feture Request: Support opus and ogg format.

### ISSUE THREAD

**Issue by Volker-Weissmann** [flackbash/AudioAnchor#59]
Feature request: Support the audio format  [opus](https://en.wikipedia.org/wiki/Opus_(audio_format)) and [ogg](https://en.wikipedia.org/wiki/Ogg).

**Comment by flackbash** [comment]
See #47.

**Comment by Volker-Weissmann** [comment]
If I rename the *.opus file to *.ogg it works just fine. So all you need to do is add "opus" to the file extension list. If you have trouble reproducing it, the *.opus is taken from [here](http://assets.alternativlos.cdn.as250.net/alternativlos-47.opus).

**Comment by flackbash** [comment]
Good to know and thanks for the link. I added `.opus` to the list of supported file extensions. However, skipping and searching does not work reliably for opus files (depending on the Android version).

If you encounter other problems with this let me know.
