### ISSUE TITLE
Automatically continue playback after navigation/alarm interrupts

### ISSUE THREAD

**Issue by hoxu** [flackbash/AudioAnchor#62]
Currently, it seems if an alarm or navigation (eg. OsmAnd) interrupts AudioAnchor, it will stop the playback. It also seems to get confused on the playback state, still showing the pause icon even though playback is already paused. This causes some bugs when trying to resume playback.

It would be nice to either always continue playback automatically or add an option to do that.

Some possible use cases:

1. Alarm/timer interrupt.
2. OsmAnd (periodic) navigation.
3. Some sports apps allow periodic status audio, which probably interrupts the same way.

Otherwise the app seems to be working fine, thanks!

**Comment by flackbash** [comment]
True, thanks for reporting this. Should be fixed now.
