### ISSUE TITLE
[Feature request] libspeex support

### ISSUE THREAD

**Issue by ResponSySS** [flackbash/AudioAnchor#65]
Hello!

First I'd like to thank you for this very lightweight and handy Android player!

I have not been able to find any information about which audio codecs AudioAnchor is able to read and I thought that libspeex, a very efficient and widely used open audio library would be one of them, but it seems it isn't the case.
It's contained by OGG and the encoder is a bit faster than that of libopus (which is why I use it a lot).

I think it could be a great addition.

Thank you for your work!

**Comment by flackbash** [comment]
I'll have a look at it. Thanks for the feedback!

**Comment by flackbash** [comment]
So basically if you have a file with an `.ogg` extension and the file can't be played, then AudioAnchor will not support this format anytime soon. AudioAnchor uses the Android [MediaPlayer](https://developer.android.com/guide/topics/media/media-formats) so any format that the Android MediaPlayer cannot handle, cannot be played by AudioAnchor.
