### ISSUE TITLE
Sleep timer quick buttons

### ISSUE THREAD

**Issue by c33s** [flackbash/AudioAnchor#71]
currently if you press on the sleep timer icon you get a dropdown with a textbox where you can enter an integer, which is enough but it could be handy to have 1-4 buttons next to the text field which have predefined (maybe even configurable) values. lets say we have `15`, `30`, `60`, `90` so i press on the 30 button and have 30mins of sleep timer.

**Comment by flackbash** [comment]
I agree, this could be useful. I'll consider it.
