### ISSUE TITLE
Info if sleep timer is running

### ISSUE THREAD

**Issue by c33s** [flackbash/AudioAnchor#72]
if you start the sleep timer there is no info about that it is running nor how long it will be running. would be nice to have such a thing

**Comment by flackbash** [comment]
This information exists. Once the sleep timer is running, the countdown is being displayed below the progress bar, between the current and the total time.
I think what you observed is a bug, which I noticed some time ago but haven't gotten around to fixing yet. I just created an issue for it in case more people stumble across it:  #73.
Basically, the sleep timer cannot be started if you have just selected an audio file for playback but haven't started the playback yet.
If this is not what you observed let me know.

**Comment by c33s** [comment]
oh i simply have overlooked the timer. would have thought to see it in the notification so it's also visible on the lock screen.
