### ISSUE TITLE
M3U playlist support

### ISSUE THREAD

**Issue by ange007** [flackbash/AudioAnchor#82]
Hi!
Do you plan to support the playlist [*.m3u](http://gonze.com/playlists/playlist-format-survey.html#M3U) format _(or other)_?
With the ability to integrate with Android _(for the ability to play through "open with", for example using G.Drive and others)_.

**Comment by r57zone** [comment]
It's probably still an application for local files, without playlists. You can download all the files from the playlist, save them to your phone and play them with this app.

**Comment by flackbash** [comment]
Right now I have no plans of implementing playlist support, but I'll keep it in mind, thanks for the suggestion.

**Comment by flackbash** [comment]
Closing this for now. I might reconsider in future or reopen this issue if there is high demand for such a functionality.
