### ISSUE TITLE
WebDAV support

### ISSUE THREAD

**Issue by idolpx** [flackbash/AudioAnchor#83]
Would be great for streaming files from NextCloud or other cloud storage solutions.

There are apps that do this for music but haven't found a good solution for audiobooks or podcasts.

**Comment by r57zone** [comment]
It seems not quite in the spirit of this application.

**Comment by flackbash** [comment]
Thanks for the suggestion.

I'm not planning on implementing this right now, but I'll keep it in mind.

**Comment by flackbash** [comment]
Closing this for now. I might reconsider in future or reopen this issue if there is high demand for such a functionality.
