### ISSUE TITLE
Directory picker not alphabetically sorted

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#87]
Currently (e.g. version 2.2.1) the directory picker, i.e. the dialog that appears when adding a new folder, or importing/exporting the database, is sorted in some random order.

Preferably can this be sorted alphabetically, ideally all folders at the top alphabetically, then all files underneath alphabetically.

**Comment by flackbash** [comment]
Yes, I agree. I don't have too much time on my hands right now, but I'll try to implement this soon.

**Comment by flackbash** [comment]
Done. Thanks for the suggestion.
