### ISSUE TITLE
Directory picker has no visual indication of folders vs files

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#88]
Currently (e.g. version 2.2.1) the directory picker, i.e. the dialog that appears when adding a new folder, or importing/exporting the database, doesn't indicate which list items are folders and which are files, e.g. with an icon to the left of the filename. It would be great if it did!

**Comment by flackbash** [comment]
Yes, agreed. Added to my Todo list :)

**Comment by flackbash** [comment]
Done.
