### ISSUE TITLE
Settings are not included in database export/import

### ISSUE THREAD

**Issue by JohnVeness** [flackbash/AudioAnchor#89]
Currently (e.g. version 2.2.1) the application settings are not included in the database export/import functionality. It would be great if they were, to help when changing to a new device (I don't like to use Google app settings backup).

**Comment by flackbash** [comment]
Right now, the export/import is really just dealing with the AudioAnchor database. Settings are stored separately, so exporting/importing them would require some more changes. I don't consider this is a high-priority issue (the functionality is rarely required - only when changing to a different device - and can also be done by hand without too much effort), so I doubt that I'll have the time to implement this any time soon.

**Comment by JohnVeness** [comment]
No worries :)

**Comment by flackbash** [comment]
Closing this for now. I might reopen this if more people request this functionality.
