### ISSUE TITLE
Add support for .m4b

### ISSUE THREAD

**Issue by zekooooo** [flackbash/AudioAnchor#9]
AFAIK .m4b files are the same as .m4a except devices like iPod parse them as books. My .m4b files seem to play fine in AudioAnchor as long as I rename them to .m4a, otherwise they aren't recognized.

It could save newbs some annoyance and the rest of us an unnecessary launch of the file manager :)

**Comment by flackbash** [comment]
The Android media player had problems with a specific file format. I thought it was m4b but maybe I confuse it with something else. Otherwise adding support for it should be no problem. I'll check soon :)

**Comment by flackbash** [comment]
I added support for .m4b files with 7c1895f6df5df1b5c3a1b9e89791b3255300ef5f so it will be in the next release.
