### ISSUE TITLE
Option to add a bookmark when "play" is pressed

### ISSUE THREAD

**Issue by BonaBeavis** [flackbash/AudioAnchor#93]
When listening to audiobooks I keep loosing my progress, either because of forgetting to set the sleep timer or by accidentally touching the progress bar. Also there could be a bug, which sometimes resets the progress, but I was not able to track it down.
A solution could be to add a bookmark when play was pressed. This list could be navigated to find the position where I stopped listening.

**Comment by flackbash** [comment]
Yes, true, I've been thinking of something like this, too.

What exactly do you mean with your proposed solution:
A bookmark is added to the current bookmark list every time the play button is pressed? Or is it a separate bookmark list containing only play-button time stamps?

What I find the most straight-forward solution to this right now is to add a special bookmark to the bookmark list when play is pressed for the first time and overwrite it whenever play is pressed again.

What are your thoughts on that?

**Comment by flackbash** [comment]
I added an option (disabled by default) to add a  `<last play position>` and a `<second to last play position>` bookmark. These are updated every time the play button is pressed.
When the option is disabled, all bookmarks with these two names are deleted again.
