### ISSUE TITLE
Feature Request: Switch completed/incomplete status by long press on icon

### ISSUE THREAD

**Issue by Mrnofish** [flackbash/AudioAnchor#95]
## Observed behavior

Long pressing an icon or an item's title triggers the same selection process.

## Desired behavior
Long press on an icon allows selection as per Material Design.
Long press on the title flips complete/incomplete status.

## Rationale
Flipping the state of an individual item requires many steps.

**Comment by flackbash** [comment]
Hmm I think a problem with this is, that it is not very intuitive. Most users will probably not expect this behavior, but assume that long-pressing the icon behaves the same as long-pressing the title or at least does not immediately do anything funny. Considering that they might by mistake lose their listening progress as a result, I prefer the user having to make a few more clicks.
