### ISSUE TITLE
Pressing Play on a completed track does not work / may cause a crash

### ISSUE THREAD

**Issue by Mrnofish** [flackbash/AudioAnchor#96]
## Observed behavior

Pressing the Play button on a completed track does not restart playing the track.
After resetting the playing position using the slider, press the Play button to restart playback, the app may force close.

## Expected behavior
Pressing the Play button on a completed track should restart playback from the beginning

**Comment by flackbash** [comment]
I actually prefer this as it is.

In any case, when autoplay is enabled, pressing the play button on a completed track should start the next (not completed) track, so one would have to implement different behaviors depending on the options set.

But I can see how someone would prefer your proposed behavior. Maybe if this is requested by more people I'll consider changing it.
