### ISSUE TITLE
Add padding to progess bar

### ISSUE THREAD

**Issue by BonaBeavis** [flackbash/AudioAnchor#97]
With those new nearly all screen mobiles, it is very easy when grabbing the phone to accidentally touch the far left or right side of the progress bar. A little bit of padding would help to avoid this.

**Comment by flackbash** [comment]
I haven't experienced this problem, but I get your point. I guess a little bit more padding wouldn't hurt.

**Comment by flackbash** [comment]
I added a bit more padding. I don't want to add much more because navigating on such a small seek bar is already hard enough for large audio files, but hopefully this will alleviate the problem.

**Comment by BonaBeavis** [comment]
It does, thanks!
