### ISSUE TITLE
Improve sleep timer

### ISSUE THREAD

**Issue by BonaBeavis** [flackbash/AudioAnchor#99]
My main use case is listening to an audiobook as a help to get to sleep. So I use the sleep timer daily and I have a suggestion to improve it:

Make the sleep timer persistent, so if it set it gets always activated when play is pressed. This prevents me from forgetting to set it and having weird dreams because the audiobook is  running the whole night. ;)

**Comment by flackbash** [comment]
I get your point. If I implemented this, this would be an extra option in the settings. However, I try not to clutter the settings too much with options that are not used by many people and can be easily replaced by making a few extra clicks.

So for now I won't add this, but if more people request this feature, I may reconsider :)

**Comment by BonaBeavis** [comment]
Ok, maybe a solution could be to implement a zoom when pressing on the scrollbar. Like when you are editing text.

![image](https://user-images.githubusercontent.com/3330855/113705432-b72c3a80-96dd-11eb-9af6-c32e35f81494.png)

**Comment by flackbash** [comment]
This is a comment for #100, right?

**Comment by flackbash** [comment]
Closing this for now. I might reopen this if there is high demand for such a functionality.
